<?php
/**
 * Created by PhpStorm.
 * User: jonaskortum
 * Date: 02.06.17
 * Time: 10:01
 */

function newsletter_registration_menu()
{
    $items['newsletter_registration'] = array(
        'type' => MENU_CALLBACK,
        'access arguments' => array('access content'),
        'page callback' => 'drupal_get_form',
        'page arguments' => array('newsletter_registration_email_input_form'),
    );

    return $items;
}

function newsletter_registration_email_input_form()
{

    $form['registration'] = array(
        '#title' => "newsletter",
        '#type' => 'fieldset',
        '#description' => ""
    );

    $form['registration']['email'] = array(
        '#type' => 'textfield',
        '#title' => t('Email'),
        '#required' => TRUE,
        '#default_value' => "",
        '#description' => "Please enter your email.",
        '#size' => 30,
        '#maxlength' => 30,
    );

    $form['registration']['first_name'] = array(
        '#type' => 'textfield',
        '#required' => TRUE,
        '#title' => t('Vorname'),
    );

    $form['registration']['last_name'] = array(
        '#type' => 'textfield',
        '#required' => TRUE,
        '#title' => t('Nachname'),
    );

    $form['registration']['gender'] = array(
        '#type' => 'radios',
        '#title' => t('Geschlecht'),
        '#required' => TRUE,
        '#options' => array(
            t('männlich'),
            t('weiblich'),
        ),);

    $form['registration']['register'] = array(
        '#type' => 'submit',
        '#value' => 'register',
        '#submit' => array('newsletter_registration_register_mail_address')
    );

    $form['registration']['sign_off'] = array(
        '#type' => 'submit',
        '#value' => 'sign off',
        '#submit' => array('newsletter_registration_sign_off_mail_address')
    );

    return $form;
}

function newsletter_registration_register_mail_address($form, &$form_state)
{

    $mail = $form_state['values']['email'];

    $is_female = $form_state['values']['gender'];

    if (!valid_email_address($mail)) {
        form_set_error('email', 'Please type in a valid mail address.');
    } else {

        $sql = "SELECT * FROM {newsletter_registration} WHERE mail_address = '" . $mail . "'";
        $result = db_query($sql);
        $found = false;

        foreach ($result as $item) {
            $found = true;
        }

        if (!$found) {

            $unique_id = newsletter_registration_generate_random_string(30);

            $first_name = $form_state['values']['first_name'];
            $last_name = $form_state['values']['last_name'];

            db_insert('newsletter_registration')
                ->fields(array('mail_address','unique_id', 'first_name', 'last_name', 'is_female'))
                ->values(array(
                    'mail_address' => $mail,
                    'unique_id' => $unique_id,
                    'first_name' => $first_name,
                    'last_name' => $last_name,
                    'is_female' => $is_female
                ))
                ->execute();
            drupal_set_message("mail successfully registered");
        } else {
            drupal_set_message('mail is already registered.', 'error');
        }
    }
}

function newsletter_registration_sign_off_mail_address($form, &$form_state)
{
    $mail = $form_state['values']['email'];

    if (!valid_email_address($mail)) {
        form_set_error('email', 'Please type in a valid mail address.');
    } else {
        $sql = "SELECT * FROM {newsletter_registration} WHERE mail_address = '" . $mail . "'";
        $result = db_query($sql);
        $found = false;

        foreach ($result as $item) {
            $found = true;
        }

        if ($found) {
            db_delete('newsletter_registration')
                ->condition('mail_address', $mail)
                ->execute();

            drupal_set_message("mail successfully signed off");
        } else {
            drupal_set_message('no mail address found.', 'error');
        }
    }
}

function newsletter_registration_generate_random_string($length)
{
    $characters = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ';
    $charactersLength = strlen($characters);
    $randomString = '';
    for ($i = 0; $i < $length; $i++) {
        $randomString .= $characters[rand(0, $charactersLength - 1)];
    }
    return $randomString;
}