<?php
/**
 * Created by PhpStorm.
 * User: jonaskortum
 * Date: 02.06.17
 * Time: 10:34
 */

require_once ("newsletter_builder_html.inc");
require_once ("newsletter_builder_save_newsletter.inc");

function newsletter_builder_menu() {

    $items['newsletter_overview'] = array(
        'type' => MENU_CALLBACK,
        'access arguments' => array('access content'),
        'page callback' => 'drupal_get_form',
        'access callback' => 'user_is_logged_in',
        'page arguments' => array('newsletter_builder_newsletter_overview_form'),
        'file' => 'newsletter_builder_show_newsletter.inc'
    );

    /*
    $items['configure_newsletter'] = array(
        'type' => MENU_CALLBACK,
        'access arguments' => array('access content'),
        'page callback' => 'drupal_get_form',
        'access callback' => true,
        'page arguments' => array('newsletter_builder_configure_newsetter_form'),
        'file' => 'newsletter_builder_configure_newsletter.inc'
    );
    */

    $items['send_newsletter/%'] = array(
        'type' => MENU_CALLBACK,
        'access callback' => true,
        'page callback' => 'newsletter_builder_build_newsletter',
    );

    $items['show_newsletter/%'] = array(
        'type' => MENU_CALLBACK,
        'access arguments' => array('access content'),
        'page callback' => 'drupal_get_form',
        'access callback' => 'user_is_logged_in',
        'page arguments' => array('newsletter_builder_show_newsletter_form'),
        'file' => 'newsletter_builder_show_newsletter.inc'
    );



    return $items;
}

function newsletter_builder_build_newsletter() {

    $node = node_load(arg(1));

    $sql = 'SELECT * FROM {newsletter_registration}';
    $result = db_query($sql);

    foreach ($result as $item) {
        $email = $item->mail_address;

        drupal_set_message($email);

        //Der Newsletter wird gebaut, ihm wird ein Betreff und ein Absender zugewiesen
        $emailBody = newsletter_builder_get_html_content($node, $item->unique_id);
        $emailSubject = "corporation newsletter";
        $emailFrom = "corporation@isum.de";

        $params = array(
            'subject' => $emailSubject,
            'body' => $emailBody,
        );

        //Die Mail wird versendet
        drupal_mail('newsletter_builder', 'newsletter', $email, language_default(), $params, $emailFrom);
        $heute = date("Y-m-d H:i:s");
        newsletter_builder_save_newsletter($node, $heute);
        drupal_set_message("Mail wurde versendet!");


    }

    return "";
}

function newsletter_builder_mail($key, &$message, $params) {
    switch($key) {
        case 'newsletter':
            $headers = array(
                'MIME-Version' => '1.0',
                'Content-Type' => 'text/html; charset=UTF-8;',
                'Content-Transfer-Encoding' => '8Bit',
                'X-Mailer' => 'Drupal'
            );

            foreach ($headers as $key => $value) {
                $message['headers'][$key] = $value;
            }
            $message['subject'] = $params['subject'];
            $message['body'] = array(0=>t($params['body']));
            break;
    }
}