<?php
/**
 * Created by PhpStorm.
 * User: jonaskortum
 * Date: 06.06.17
 * Time: 07:28
 */

function newsletter_event_participation_menu()
{

    $items['newsletter_interest/%/%'] = array(
        'type' => MENU_CALLBACK,
        'access callback' => true,
        'page callback' => 'newsletter_event_participation_interest',
    );

    $items['newsletter_no_interest/%/%'] = array(
        'type' => MENU_CALLBACK,
        'access callback' => true,
        'page callback' => 'newsletter_event_participation_no_interest',
    );

    $items['newsletter_participation/%/%'] = array(
        'type' => MENU_CALLBACK,
        'access callback' => true,
        'page callback' => 'newsletter_event_participation_participation',
    );

    $items['newsletter_no_participation/%/%'] = array(
        'type' => MENU_CALLBACK,
        'access callback' => true,
        'page callback' => 'newsletter_event_participation_no_participation',
    );

    return $items;

}


/*
 * Erweitert die Anzeige des Nodes um die Nutzer-Tabelle
 */
function newsletter_event_participation_node_view($node, $view_mode, $langcode)
{
    $test = $node->type;

    if (!strcmp($test, "ausschreibung")) {

        global $base_url;
        if ($node = menu_get_object()) {
            // Get the nid
            $nid = $node->nid;
        } else {
            $nid = 0;
        }

        $node2 = $base_url . "/send_newsletter/" . $nid;


        $tempString = "<br><br><br><button onclick=\"window.location.href='$node2'\" type=\"button\" id=\"send\">Per Newsletter versenden</button> ";

        $node->content['my_additional_field2'] = array(
            '#markup' => t($tempString),
            '#weight' => 1000,
        );
    }
}

function newsletter_event_participation_no_interest()
{

    $nid = arg(1);
    $unique_id = arg(2);

    $node = node_load($nid);

    if (!empty($node)) {
        $user_counter = 0;
        $sql = "SELECT * FROM {newsletter_registration} WHERE unique_id = '" . $unique_id . "'";
        $result = db_query($sql);

        foreach ($result as $item) {
            $user_counter++;
        }

        if ($user_counter == 1) {

            $sql = "SELECT * FROM {newsletter_participation} WHERE nid = " . $nid . " AND unique_user_id = '" . $unique_id . "'";
            $result = db_query($sql);

            foreach ($result as $item) {
                $found_user = $item;
            }

            if (!empty($found_user)) {
                if ($found_user->interest != 0) {
                    db_update('newsletter_participation')
                        ->fields(array(
                            'interest' => 0,
                        ))
                        ->condition('nid', $nid)
                        ->condition('unique_user_id', $unique_id)
                        ->execute();
                }
            } else {
                db_insert('newsletter_participation')
                    ->fields(array('nid', 'unique_user_id', 'interest'))
                    ->values(array(
                        'nid' => $nid,
                        'unique_user_id' => $unique_id,
                        'interest' => 0,
                    ))
                    ->execute();
            }

            $user = newsletter_event_participation_get_user_information($unique_id);
            drupal_set_message("Hallo ".$user->first_name . " " . $user->last_name.". Sie interessieren sich ab sofort nicht mehr für dieses Objekt.");

        } else {
            drupal_set_message("no user with this id found. Please contact the administrator");
        }

    } else {
        drupal_set_message("no node with this id found. Please contact the administrator", 'error');
    }


    return "";
}

function newsletter_event_participation_interest()
{

    $nid = arg(1);
    $unique_id = arg(2);

    $node = node_load($nid);

    if (!empty($node)) {
        $user_counter = 0;
        $sql = "SELECT * FROM {newsletter_registration} WHERE unique_id = '" . $unique_id . "'";
        $result = db_query($sql);

        foreach ($result as $item) {
            $user_counter++;
        }

        if ($user_counter == 1) {
            $sql = "SELECT * FROM {newsletter_participation} WHERE nid = " . $nid . " AND unique_user_id = '" . $unique_id . "'";
            $result = db_query($sql);


            foreach ($result as $item) {
                $found_user = $item;
            }

            if (!empty($found_user)) {
                if ($found_user->interest != 1) {
                    db_update('newsletter_participation')
                        ->fields(array(
                            'interest' => 1,
                        ))
                        ->condition('nid', $nid)
                        ->condition('unique_user_id', $unique_id)
                        ->execute();
                }
            } else {
                db_insert('newsletter_participation')
                    ->fields(array('nid', 'unique_user_id', 'interest'))
                    ->values(array(
                        'nid' => $nid,
                        'unique_user_id' => $unique_id,
                        'interest' => 1,
                    ))
                    ->execute();

            }

            $user = newsletter_event_participation_get_user_information($unique_id);
            drupal_set_message("Hallo ".$user->first_name . " " . $user->last_name.". Sie interessieren sich ab sofort für dieses Objekt.");

        } else {
            drupal_set_message("no user with this id found. Please contact the administrator");
        }

    } else {
        drupal_set_message("no node with this id found. Please contact the administrator", 'error');
    }


    return "";
}

function newsletter_event_participation_no_participation()
{

    $nid = arg(1);
    $unique_id = arg(2);

    $node = node_load($nid);

    if (!empty($node)) {
        $user_counter = 0;
        $sql = "SELECT * FROM {newsletter_registration} WHERE unique_id = '" . $unique_id . "'";
        $result = db_query($sql);

        foreach ($result as $item) {
            $user_counter++;
        }

        if ($user_counter == 1) {
            $sql = "SELECT * FROM {newsletter_participation} WHERE nid = " . $nid . " AND unique_user_id = '" . $unique_id . "'";
            $result = db_query($sql);


            foreach ($result as $item) {
                $found_user = $item;
            }

            if (!empty($found_user)) {
                if ($found_user->participation != 0) {
                    db_update('newsletter_participation')
                        ->fields(array(
                            'participation' => 0,
                        ))
                        ->condition('nid', $nid)
                        ->condition('unique_user_id', $unique_id)
                        ->execute();
                }
            } else {
                db_insert('newsletter_participation')
                    ->fields(array('nid', 'unique_user_id', 'participation'))
                    ->values(array(
                        'nid' => $nid,
                        'unique_user_id' => $unique_id,
                        'participation' => 0,
                    ))
                    ->execute();

            }
            $user = newsletter_event_participation_get_user_information($unique_id);
            drupal_set_message("Hallo ".$user->first_name . " " . $user->last_name.". Sie nehmen ab sofort nicht mehr an diesem Objekt teil.");

        } else {
            drupal_set_message("no user with this id found. Please contact the administrator");
        }

    } else {
        drupal_set_message("no node with this id found. Please contact the administrator", 'error');
    }


    return "";

}

function newsletter_event_participation_participation()
{

    $nid = arg(1);
    $unique_id = arg(2);

    $node = node_load($nid);

    if (!empty($node)) {
        $user_counter = 0;
        $sql = "SELECT * FROM {newsletter_registration} WHERE unique_id = '" . $unique_id . "'";
        $result = db_query($sql);

        foreach ($result as $item) {
            $user_counter++;
        }

        if ($user_counter == 1) {
            $sql = "SELECT * FROM {newsletter_participation} WHERE nid = " . $nid . " AND unique_user_id = '" . $unique_id . "'";
            $result = db_query($sql);


            foreach ($result as $item) {
                $found_user = $item;
            }

            if (!empty($found_user)) {
                if ($found_user->participation != 1) {
                    db_update('newsletter_participation')
                        ->fields(array(
                            'interest' => 1,
                            'participation' => 1,
                        ))
                        ->condition('nid', $nid)
                        ->condition('unique_user_id', $unique_id)
                        ->execute();
                }
            } else {
                db_insert('newsletter_participation')
                    ->fields(array('nid', 'unique_user_id', 'interest', 'participation'))
                    ->values(array(
                        'nid' => $nid,
                        'unique_user_id' => $unique_id,
                        'interest' => 1,
                        'participation' => 1,
                    ))
                    ->execute();

            }
            $user = newsletter_event_participation_get_user_information($unique_id);
            drupal_set_message("Hallo ".$user->first_name . " " . $user->last_name.". Sie nehmen ab sofort an diesem Objekt teil.");

        } else {
            drupal_set_message("no user with this id found. Please contact the administrator");
        }

    } else {
        drupal_set_message("no node with this id found. Please contact the administrator", 'error');
    }


    return "";
}

function newsletter_event_participation_get_user_information($unique_id) {

    $user = "";

    $sql = "SELECT * FROM {newsletter_registration} WHERE unique_id = '".$unique_id."'";

    $result = db_query($sql);
    foreach ($result as $item) {
        $user = $item;
    }

    return $user;
}

